/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cantometro.view;

import java.awt.event.ActionListener;

/**
 *
 * @author alberto
 */
public class ControlPanel extends javax.swing.JFrame {
    
    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        
        initComponents();
        this.setTitle("Camtometro: Panel de Control");
        this.setLocationRelativeTo(null);
        
    
    }
    
    public void setActionListener(ActionListener al) {
        
        this.cerrarSesion_button.addActionListener(al);
        this.evaluar_button.addActionListener(al);
        this.listarAlumnos_button.addActionListener(al);
        this.nuevoAlumno_button.addActionListener(al);
        this.exportarDatos_button.addActionListener(al);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoAlumno_button = new javax.swing.JButton();
        exportarDatos_button = new javax.swing.JButton();
        evaluar_button = new javax.swing.JButton();
        listarAlumnos_button = new javax.swing.JButton();
        PanelDeControl_Label = new javax.swing.JLabel();
        cerrarSesion_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoAlumno_button.setText("NUEVO ALUMNO");
        nuevoAlumno_button.setActionCommand("CP_NEWALUMNO");

        exportarDatos_button.setText("EXPORTAR DATOS");
        exportarDatos_button.setActionCommand("CP_EXPORTAR");

        evaluar_button.setText("EVALUAR");
        evaluar_button.setActionCommand("CP_EVALUAR");

        listarAlumnos_button.setText("LISTAR ALUMNOS");
        listarAlumnos_button.setActionCommand("CP_LISTARALUMNOS");
        listarAlumnos_button.setMaximumSize(new java.awt.Dimension(136, 32));
        listarAlumnos_button.setMinimumSize(new java.awt.Dimension(136, 32));

        PanelDeControl_Label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelDeControl_Label.setText("PANEL DE CONTROL");

        cerrarSesion_button.setText("CERRAR SESION");
        cerrarSesion_button.setActionCommand("CP_LOGOUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(PanelDeControl_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrarSesion_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nuevoAlumno_button, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(evaluar_button, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listarAlumnos_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exportarDatos_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(PanelDeControl_Label)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listarAlumnos_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoAlumno_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exportarDatos_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evaluar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrarSesion_button)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PanelDeControl_Label;
    private javax.swing.JButton cerrarSesion_button;
    private javax.swing.JButton evaluar_button;
    private javax.swing.JButton exportarDatos_button;
    private javax.swing.JButton listarAlumnos_button;
    private javax.swing.JButton nuevoAlumno_button;
    // End of variables declaration//GEN-END:variables
}