/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cantometro.view;

import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author alberto
 */
public class Login extends javax.swing.JFrame {
    
    //private ArrayList<Profesor> profesores;
    
    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        
        //this.profesores = profesores;
        this.setTitle("Cantometro: Alta Profesor");
        this.setLocationRelativeTo(null);
        
        
    }
    
    public void setActionListener(ActionListener al) {
        
       this.alta_button.addActionListener(al);
       this.entrar_button.addActionListener(al);
        
    }
    
    public ArrayList getLoginFields() {
        
        ArrayList al = new ArrayList();
        
        al.add(this.user_textField.getText());
        al.add(this.password_passwordField.getText());
        
        return al;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_textField = new javax.swing.JTextField();
        password_passwordField = new javax.swing.JPasswordField();
        Label_Usuario = new javax.swing.JLabel();
        Label_Contraseña = new javax.swing.JLabel();
        Label_NUEVOPROFE = new javax.swing.JLabel();
        entrar_button = new javax.swing.JButton();
        alta_button = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(340, 230));

        Label_Usuario.setText("Usuario:");

        Label_Contraseña.setText("Contraseña: ");

        Label_NUEVOPROFE.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_NUEVOPROFE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_NUEVOPROFE.setText("LOGIN");

        entrar_button.setText("ENTRAR");
        entrar_button.setActionCommand("LOGIN_ENTRAR");

        alta_button.setText("ALTA");
        alta_button.setActionCommand("LOGIN_ALTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(alta_button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(entrar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Label_NUEVOPROFE, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Label_Usuario)
                        .addGap(14, 14, 14)
                        .addComponent(user_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(Label_Contraseña)
                        .addGap(14, 14, 14)
                        .addComponent(password_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Label_NUEVOPROFE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Label_Usuario))
                    .addComponent(user_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Label_Contraseña))
                    .addComponent(password_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alta_button)
                    .addComponent(entrar_button))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 113, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 114, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Contraseña;
    private javax.swing.JLabel Label_NUEVOPROFE;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JButton alta_button;
    private javax.swing.JButton entrar_button;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPasswordField password_passwordField;
    private javax.swing.JTextField user_textField;
    // End of variables declaration//GEN-END:variables
}
