/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cantometro.view;


import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author alberto
 */
public class NewAlumno extends javax.swing.JFrame {
    
    /**
     * Creates new form NuevoAlumno
     */
    public NewAlumno() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public void setActionListener(ActionListener al) {
        
        this.borrar_button.addActionListener(al);
        this.crear_button.addActionListener(al);
        this.cerrar_Button.addActionListener(al);
        
    }
    
    public ArrayList getNewAlumnoFields() {
        
        ArrayList al = new ArrayList();
        
        al.add(this.nombre_textField.getText());
        al.add(this.apellidos_textField.getText());
        al.add(this.nia_textField.getText());
        al.add(this.curso_comboBox.getSelectedItem().toString());
        
        return al;
    }
    
    public void flush() {
        
        this.nombre_textField.setText("");
        this.apellidos_textField.setText("");
        this.nia_textField.setText("");
        this.curso_comboBox.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apellidos_textField = new javax.swing.JTextField();
        nia_textField = new javax.swing.JTextField();
        curso_comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        crear_button = new javax.swing.JButton();
        cerrar_Button = new javax.swing.JButton();
        borrar_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nombre_textField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        curso_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º Elemental", "2º Elemental", "3º Elemental", "4º Elemental" }));

        jLabel1.setText("Nombre:");

        jLabel2.setText("NIA:");

        jLabel3.setText("Curso:");

        crear_button.setText("CREAR");
        crear_button.setActionCommand("NA_CREAR");

        cerrar_Button.setText("CERRAR");
        cerrar_Button.setActionCommand("NA_CERRAR");

        borrar_button.setText("BORRAR");
        borrar_button.setActionCommand("NA_BORRAR");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("NUEVO ALUMNO");

        jLabel4.setText("Apellidos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cerrar_Button)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre_textField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrar_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crear_button, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addComponent(curso_comboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nia_textField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidos_textField))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nia_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curso_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_button)
                    .addComponent(borrar_button)
                    .addComponent(cerrar_Button))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos_textField;
    private javax.swing.JButton borrar_button;
    private javax.swing.JButton cerrar_Button;
    private javax.swing.JButton crear_button;
    private javax.swing.JComboBox<String> curso_comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nia_textField;
    private javax.swing.JTextField nombre_textField;
    // End of variables declaration//GEN-END:variables

    
}
