/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cantometro.view;

import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author Alberto Aloy Pérez
 */
public class Settings extends javax.swing.JFrame {

    private boolean algoLleno;
    private boolean inputLleno;
    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        algoLleno = false;
        inputLleno = false;
        this.setLocationRelativeTo(null);
    }
    
    public void setActionListener(ActionListener al) {
        
        this.aplicar_button.addActionListener(al);
        this.cancelar_button.addActionListener(al);
        
    }
    
    public void populateComboBoxAlgoritmos(ArrayList algos) {
        
        if(!algoLleno) {
            for(int i = 0; i < algos.size(); i++) {
                algoritmos_comboBox.addItem(algos.get(i).toString());
            }
            
            algoLleno = true;
        }
        
    }
    
    public void populateComboBoxInputs(ArrayList inputs) {
        if(!inputLleno) {
            for(int i = 0; i < inputs.size(); i++) {
                inputs_comboBox.addItem(inputs.get(i).toString());
            }
            
            inputLleno = true;
        }
    }
    
    public ArrayList getSettingsSeleccionados() {
        
        ArrayList newSettings = new ArrayList();
        
        String algo = this.algoritmos_comboBox.getSelectedItem().toString();
        String input = this.inputs_comboBox.getSelectedItem().toString();
        
        newSettings.add(algo);
        newSettings.add(input);
        
        return newSettings;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrada_label = new javax.swing.JLabel();
        inputs_comboBox = new javax.swing.JComboBox<>();
        algoritmos_comboBox = new javax.swing.JComboBox<>();
        settings_label = new javax.swing.JLabel();
        algoritmo_label = new javax.swing.JLabel();
        cancelar_button = new javax.swing.JButton();
        aplicar_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entrada_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        entrada_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrada_label.setText("Entrada:");
        entrada_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        inputs_comboBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        algoritmos_comboBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        settings_label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        settings_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings_label.setText("SETTINGS");
        settings_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        algoritmo_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        algoritmo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algoritmo_label.setText("Algoritmo:");
        algoritmo_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        cancelar_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cancelar_button.setText("CANCELAR");
        cancelar_button.setActionCommand("ST_CANCEL");

        aplicar_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aplicar_button.setText("APLICAR");
        aplicar_button.setActionCommand("ST_APLICAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settings_label, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entrada_label)
                            .addComponent(algoritmo_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(algoritmos_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputs_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aplicar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(cancelar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(settings_label)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(algoritmos_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algoritmo_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputs_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrada_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aplicar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algoritmo_label;
    private javax.swing.JComboBox<String> algoritmos_comboBox;
    private javax.swing.JButton aplicar_button;
    private javax.swing.JButton cancelar_button;
    private javax.swing.JLabel entrada_label;
    private javax.swing.JComboBox<String> inputs_comboBox;
    private javax.swing.JLabel settings_label;
    // End of variables declaration//GEN-END:variables
}
